# Generated by Django 4.1.5 on 2023-06-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="unit",
        ),
    ]
