# Generated by Django 4.1.5 on 2023-02-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_recipe"),
        ("accounts", "0002_invitecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="expires",
            field=models.DateTimeField(
                default=accounts.models.invite_code_default_expiry
            ),
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hidden_recipe_ingredients",
                    models.ManyToManyField(to="core.ingredient"),
                ),
                ("hidden_recipe_tags", models.ManyToManyField(to="core.tag")),
            ],
        ),
    ]
